### ISSUE TITLE
Testers wanted.

### ISSUE THREAD

**Issue by systemroot** [systemroot/ogars-bots-blocker#1]
To do what i think is needed to get some logs when bot's connect. 
but idk how to make bots for ogar's server. so if some one have a script or anything else please comment here. i don't want the script. just i'll give you my server ip and you will add bots' and i'll get my logs! 

after this maybe i will be able to block those!
also i'm on discord https://discord.gg/sMMmpGz

**Comment by systemroot** [comment]
- [x] **``Polarsbots.tk Godbye !``**
- [ ] **``Who's next?!``**

**Comment by dada211** [comment]
hi I have bots (clone)

**Comment by systemroot** [comment]
you have bot's script to make tests?! 
or someone is adding bots on your server?!
