### ISSUE TITLE
Server address

### ISSUE THREAD

**Issue by Gimmo** [systemroot/ogars-bots-blocker#4]
You wrote:
`The only problem with this way is because if anyone will try to scan your ports one by one can find your real server port! the chance about this from 100, is 20-25 xP.`

But if you change in gameserver.ini (MultiOgar) `serverBind = "0.0.0.0"` to `serverBind = "127.0.0.1"` then real port of server will be visible for nginx, but not visible from the world. Am I wrong?

**Comment by systemroot** [comment]
yes you are right!!
i triend and that worked i can't connect ex on port directly just in nginx port!
thanks for letting me to know!

**Comment by systemroot** [comment]
btw you will not ble able to publish your server in gametrackers (ex ogar-tracker.tk) anymore :confused:

**Comment by Gimmo** [comment]
Thanks.
