### ISSUE TITLE
Hello Systemroot :)

### ISSUE THREAD

**Issue by Conor219** [systemroot/ogars-bots-blocker#6]
Hi, I have some problems with my server and I would like to use your script. But I'd like to talk to you privately. Could you give me your Skype? Please.
Thank you :D

**Comment by systemroot** [comment]
sure, but the problem is i don't use skype, 
btw we can talk somewhere else, ex on fb.com/dope.boy66
else if whatsapp +355675557657
or anywhere else you want! we can talk somewhere and we can use teamviewer if you want help on installation or idk.
